# migrations/versions/832c157e58c3_core_persistence_ingestion_files_raw_.py
"""core persistence: ingestion files, raw transactions, audit log

Revision ID: 832c157e58c3
Revises: bcfb34c8d29f
Create Date: 2026-09-23 10:24:58.456681

WP1 Increment 4. Creates the three tables needed to unblock CSV ingestion
and to complete the audit append-only mechanism started in bcfb34c8d29f.

Hand-written rather than autogenerated: Alembic's autogenerate does not
reliably diff PostgreSQL declarative partitioning (raw_transactions is
PARTITION BY RANGE (ingested_on) per R92/A6.2), so this migration is
authored directly. migrations/env.py's target_metadata is now wired to
recon.persistence.models.Base.metadata, so a future non-partitioned table
could use autogenerate — this one still doesn't, for consistency within
one migration.

Partition strategy (honest scope note): monthly partitions are created for
2025-01 through 2026-12 plus a DEFAULT partition for anything outside that
window. This is enough for real partition pruning to work against the
assessment's sample data (dated March 2026) and the golden dataset.
Automated partition creation/rotation for ongoing operation — so the table
doesn't silently fall back to DEFAULT after December 2026 — is deferred to
WP6 (docs/PERFORMANCE.md); not implemented here.

Audit privilege note (see also bcfb34c8d29f): GRANT/REVOKE never restrict
a table's OWNER. This migration runs as recon_app, so recon_app owns
audit.audit_log, and the REVOKE statements below do not by themselves stop
recon_app from mutating a row — REVOKE only closes that door for
recon_audit and any other non-owner role. The BEFORE UPDATE OR DELETE
trigger created below closes the gap for the owner too: triggers fire
regardless of role, including the table owner. In application code, only
a session authenticated as recon_audit (see AUDIT_DB_USER /
AUDIT_DB_PASSWORD, recon.persistence.session.get_audit_engine) writes to
audit_log in normal operation; recon_app's own connection should never
issue writes to this table, but the trigger is what makes that a
guarantee rather than a convention, and is exercised directly by
tests/integration/test_audit_log_append_only.py.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "832c157e58c3"
down_revision: str | None = "bcfb34c8d29f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _monthly_partition_bounds(start: date, end: date) -> list[tuple[date, date]]:
    """(from, to) month boundaries between start (inclusive) and end (exclusive)."""
    bounds: list[tuple[date, date]] = []
    current = start
    while current < end:
        december = 12
        nxt = (
            date(current.year + 1, 1, 1)
            if current.month == december
            else date(current.year, current.month + 1, 1)
        )
        bounds.append((current, nxt))
        current = nxt
    return bounds


def upgrade() -> None:
    # ------------------------------------------------------------------
    # ingestion_files
    # ------------------------------------------------------------------
    op.create_table(
        "ingestion_files",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("bank_code", sa.String(20), nullable=False),
        sa.Column("format_type", sa.String(20), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(64), nullable=False, unique=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("statement_period_start", sa.Date(), nullable=True),
        sa.Column("statement_period_end", sa.Date(), nullable=True),
        sa.Column("statement_number", sa.String(50), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("ingested_by", sa.String(100), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="PENDING"),
        sa.Column("record_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("parse_error_count", sa.Integer(), nullable=False, server_default="0"),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PARSED', 'PARTIALLY_PARSED', 'FAILED', 'REJECTED_DUPLICATE')",
            name="status_valid",
        ),
        sa.CheckConstraint("size_bytes >= 0", name="size_bytes_non_negative"),
        sa.CheckConstraint("record_count >= 0", name="record_count_non_negative"),
        sa.CheckConstraint("parse_error_count >= 0", name="parse_error_count_non_negative"),
    )

    # ------------------------------------------------------------------
    # raw_transactions: partitioned by RANGE (ingested_on)
    # ------------------------------------------------------------------
    op.create_table(
        "raw_transactions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("ingested_on", sa.Date(), nullable=False),
        sa.Column(
            "ingestion_file_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("ingestion_files.id", name="fk_raw_transactions_ingestion_file_id"),
            nullable=False,
        ),
        sa.Column("bank_code", sa.String(20), nullable=False),
        sa.Column("format_type", sa.String(20), nullable=False),
        sa.Column("source_line_no", sa.Integer(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(), nullable=False),
        sa.Column("parse_status", sa.String(20), nullable=False, server_default="PENDING"),
        sa.Column("parse_errors", postgresql.JSONB(), nullable=True),
        sa.PrimaryKeyConstraint("id", "ingested_on", name="pk_raw_transactions"),
        sa.CheckConstraint(
            "parse_status IN ('PENDING', 'PARSED', 'FAILED', 'QUARANTINED')",
            name="parse_status_valid",
        ),
        postgresql_partition_by="RANGE (ingested_on)",
    )

    op.create_index(
        "ix_raw_transactions_file_line",
        "raw_transactions",
        ["ingestion_file_id", "source_line_no"],
    )
    op.create_index(
        "ix_raw_transactions_ingested_on_brin",
        "raw_transactions",
        ["ingested_on"],
        postgresql_using="brin",
    )

    for lower, upper in _monthly_partition_bounds(date(2025, 1, 1), date(2027, 1, 1)):
        partition_name = f"raw_transactions_{lower.strftime('%Y_%m')}"
        op.execute(
            f"""
            CREATE TABLE {partition_name}
            PARTITION OF raw_transactions
            FOR VALUES FROM ('{lower.isoformat()}') TO ('{upper.isoformat()}')
            """
        )
    op.execute(
        """
        CREATE TABLE raw_transactions_default
        PARTITION OF raw_transactions DEFAULT
        """
    )

    # ------------------------------------------------------------------
    # audit.audit_log
    # ------------------------------------------------------------------
    op.create_table(
        "audit_log",
        sa.Column(
            "event_id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("chain_id", sa.String(100), nullable=False),
        sa.Column("sequence_no", sa.BigInteger(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("actor_type", sa.String(20), nullable=False),
        sa.Column("actor_id", sa.String(100), nullable=False),
        sa.Column("action_type", sa.String(30), nullable=False),
        sa.Column("affected_records", postgresql.JSONB(), nullable=False),
        sa.Column("before_state", postgresql.JSONB(), nullable=True),
        sa.Column("after_state", postgresql.JSONB(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("prev_hash", sa.CHAR(64), nullable=True),
        sa.Column("current_hash", sa.CHAR(64), nullable=False, unique=True),
        sa.Column("serialisation_version", sa.SmallInteger(), nullable=False),
        sa.UniqueConstraint("chain_id", "sequence_no", name="uq_audit_log_chain_id_sequence_no"),
        sa.CheckConstraint("actor_type IN ('SYSTEM', 'USER')", name="actor_type_valid"),
        schema="audit",
    )
    op.create_index(
        "ix_audit_log_occurred_at_brin",
        "audit_log",
        ["occurred_at"],
        postgresql_using="brin",
        schema="audit",
    )
    op.create_index(
        "ix_audit_log_action_type_occurred_at",
        "audit_log",
        ["action_type", "occurred_at"],
        schema="audit",
    )
    op.create_index(
        "ix_audit_log_affected_records_gin",
        "audit_log",
        ["affected_records"],
        postgresql_using="gin",
        schema="audit",
    )

    # Explicit grants — belt-and-braces alongside the ALTER DEFAULT
    # PRIVILEGES set in bcfb34c8d29f. See the module docstring above for
    # why this alone is still not sufficient.
    op.execute("GRANT INSERT, SELECT ON audit.audit_log TO recon_audit")
    op.execute("REVOKE UPDATE, DELETE ON audit.audit_log FROM recon_audit")

    # Defence-in-depth trigger: blocks UPDATE and DELETE for every role,
    # including the table owner. This is the mechanism that actually
    # enforces append-only — see the module docstring above.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit.forbid_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'audit.audit_log is append-only: % on event_id=% is not permitted',
                TG_OP,
                OLD.event_id;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_forbid_mutation
        BEFORE UPDATE OR DELETE ON audit.audit_log
        FOR EACH ROW
        EXECUTE FUNCTION audit.forbid_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_forbid_mutation ON audit.audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit.forbid_mutation()")
    op.drop_table("audit_log", schema="audit")
    op.drop_table("raw_transactions")  # drops all partitions with it
    op.drop_table("ingestion_files")
